# Generated by Django 5.2.5 on 2025-12-20 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_app', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware_app.user')),
            ],
        ),
    ]
